### PR TITLE
Specify args.nix file

### PR DESCRIPTION
**Pull request by infinisil**
This came out of discussions with @roberth and is an alternative to #27

### CODE REVIEW

**Comment by roberth** [comment]
For full generality, we may also consider an optional file like `pkgs-attr.nix`, with contents like
```nix
pkgs: pkgs.callPackage ./pkg-fun.nix { python = pkgs.python3; }
```

**Comment by DavHau** [comment]
This looks looks great. I would like to add that we might want to discourage using any function definitions inside args.nix. So the requirement would be that the args.nix file is JSON/TOML serializable.

That would:
- prevent people from inline calling `overrideAttrs` on a dependency.
- enforce private dependency variants to be explicitly declared in an extra file.
- allow third party tools to make sense of what is happening inside nixpkgs.
- simplify automation approaches that need to parse information from packages.
- simplify automation approaches that need to generate or modify package variants.

That restriction would imply that the args.nix cannot be a function itself, like it is in the current approach. But this should not be a problem because it is just a mapping of names.
Example:
`foo/args.nix`:
```nix
{
  hello = "hello-with-openssl";
  bar = "bar-for-foo";
  withSystemd = true;
  python3 = "python38";
}
```

It would specifically not allow something like:
`foo/args.nix`
```
  hello = hello.overrideAttrs (old: ...)
```
Therefore the user is forced to create a new package hello for foo, which is good because that allows an outsider to reference the custom hello package which can be beneficial for modifying it. Otherwise the user would have to copy the inline definition of the custom hello.

We probably wouldn't want to expose private package variations like `bar-for-foo` via the global `pkgs`, but they should be exposed somewhere I believe, and definitely be declared in an extra file.
If there is a 1 to 1 mapping between every existing package in nixpkgs to a file location, that would be simply amazing.

**Comment by roberth** [comment]
I disagree.

This solution is already a solution to relax a forced form (`callPackage x { }`). By imposing yet more restrictions to the arguments, we'll end up having to define even more such relaxations.

These aren't features. They're workaround for arbitrarily imposed restrictions that didn't need to be there in the first place.

Do we really want people to learn these rather useless non-abstractions, or do we want the code to be simple, self-explanatory and flexible?

> If there is a 1 to 1 mapping between every existing package in nixpkgs to a file location, that would be simply amazing.

It would completely deny the functional nature of Nixpkgs, and it will not work for generated package sets. We might as well write the .drvs by hand if this is to be a goal.

Also, friendly reminder that complexity necessarily comes with a limited budget. If we spend it on implementing arbitrary "architecture" rules we can't spend it on improving real functionality or real developer experience.

**Comment by infinisil** [comment]
In the last meeting we decided to not pursue this further and instead for a simpler fix, which is discussed in #27

**Pull request closed without merging**
